=== Ashegham/webref/schemas/extract-css.json
{
  "$schema": "http://json-schema.org/schema#",
  "$id": "https://w3c.github.io/webref/schemas/extract-css.json",

  "type": "object",
  "additionalProperties": false,
  "required": ["spec", "properties", "atrules", "valuespaces"],
  "properties": {
    "spec": { "$ref": "common.json#/$defs/specInExtract" },

    "properties": {
      "type": "object",
      "propertyNames": { "$ref": "common.json#/$defs/cssPropertyName" },
      "additionalProperties": {
        "type": "object",
        "additionalProperties": true,
        "properties": {
          "name": { "$ref": "common.json#/$defs/cssPropertyName" },
          "value": { "$ref": "common.json#/$defs/cssValue" },
          "styleDeclaration": {
            "type": "array",
            "items": { "type": "string" },
            "minItems": 1
          }
        }
      }
    },

    "atrules": {
      "type": "object",
      "propertyNames": {
        "type": "string",
        "pattern": "^@"
      },
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "value": { "$ref": "common.json#/$defs/cssValue" },
          "descriptors": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": true,
              "properties": {
                "name": { "type": "string" },
                "for": { "type": "string" },
                "value": { "$ref": "common.json#/$defs/cssValue" }
              }
            }
          }
        }
      }
    },

    "valuespaces": {
      "type": "object",
      "propertyNames": {
        "type": "string",
        "pattern": "^<[^>]+>$"
      },
      "additionalProperties": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "prose": { "type": "string" },
          "value": { "$ref": "common.json#/$defs/cssValue" },
          "legacyValue": { "$ref": "common.json#/$defs/cssValue" }
        }
      }
    }
  }
}

=== Ashegham/webref/ed/css/css-anchor.json
{
  "spec": {
    "title": "CSS Anchor Positioning",
    "url": "https://drafts.csswg.org/css-anchor-1/"
  },
  "properties": {
    "anchor-name": {
      "name": "anchor-name",
      "value": "none | <dashed-ident>",
      "initial": "none",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "as specified",
      "canonicalOrder": "per grammar",
      "animationType": "discrete",
      "styleDeclaration": [
        "anchor-name",
        "anchorName"
      ]
    },
    "position-fallback": {
      "name": "position-fallback",
      "value": "none | <dashed-ident>",
      "initial": "none",
      "appliesTo": "absolutely-positioned elements",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "as specified",
      "canonicalOrder": "per grammar",
      "animationType": "discrete",
      "styleDeclaration": [
        "position-fallback",
        "positionFallback"
      ]
    }
  },
  "atrules": {
    "@position-fallback": {
      "value": "@position-fallback <dashed-ident> { <rule-list> } @try { <declaration-list> }",
      "descriptors": []
    }
  },
  "valuespaces": {
    "<anchor()>": {
      "prose": "An absolutely-positioned element can use the anchor() function as a value in its inset properties to refer to the position of one or more anchor elements. The anchor() function resolves to a <length>.",
      "value": "anchor( <dashed-ident>? <anchor-side>, <length-percentage>? )"
    },
    "<anchor-size()>": {
      "prose": "An absolutely-positioned element can use the anchor-size() function in its sizing properties to refer to the size of one or more anchor elements. The anchor-size() function resolves to a <length>.",
      "value": "anchor( <dashed-ident>? <anchor-size>, <length-percentage>? )"
    },
    "<anchor-side>": {
      "value": "top | left | right | bottom | start | end | self-start | self-end | <percentage> | center"
    },
    "<anchor-size>": {
      "value": "width | height | block | inline | self-block | self-inline"
    }
  }
}

=== Ashegham/webref/ed/css/css-will-change.json
{
  "spec": {
    "title": "CSS Will Change Module Level 1",
    "url": "https://drafts.csswg.org/css-will-change-1/"
  },
  "properties": {
    "will-change": {
      "name": "will-change",
      "value": "auto | <animateable-feature>#",
      "initial": "auto",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "specified value",
      "canonicalOrder": "per grammar",
      "animationType": "not animatable",
      "styleDeclaration": [
        "will-change",
        "willChange"
      ]
    }
  },
  "atrules": {},
  "valuespaces": {
    "<animateable-feature>": {
      "value": "scroll-position | contents | <custom-ident>"
    }
  }
}

=== Ashegham/webref/ed/css/css-shared-element-transitions.json
{
  "spec": {
    "title": "CSS Shared Element Transitions Module Level 1",
    "url": "https://drafts.csswg.org/css-shared-element-transitions-1/"
  },
  "properties": {
    "page-transition-tag": {
      "name": "page-transition-tag",
      "value": "none | <custom-ident>",
      "initial": "none",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "as specified",
      "canonicalOrder": "per grammar",
      "animationType": "discrete",
      "styleDeclaration": [
        "page-transition-tag",
        "pageTransitionTag"
      ]
    }
  },
  "atrules": {},
  "valuespaces": {
    "<pt-tag-selector>": {
      "value": "'*' | <custom-ident>"
    }
  }
}

=== Ashegham/webref/tr/css/scroll-animations.json
{
  "spec": {
    "title": "Scroll-linked Animations",
    "url": "https://drafts.csswg.org/scroll-animations-1/"
  },
  "properties": {
    "scroll-timeline-name": {
      "name": "scroll-timeline-name",
      "value": "none | <custom-ident>",
      "initial": "none",
      "appliesTo": "scroll containers",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "the specified keyword",
      "canonicalOrder": "per grammar",
      "animationType": "not animatable",
      "styleDeclaration": [
        "scroll-timeline-name",
        "scrollTimelineName"
      ]
    },
    "scroll-timeline-axis": {
      "name": "scroll-timeline-axis",
      "value": "block | inline | vertical | horizontal",
      "initial": "block",
      "appliesTo": "scroll containers",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "the specified keyword",
      "canonicalOrder": "per grammar",
      "animationType": "not animatable",
      "styleDeclaration": [
        "scroll-timeline-axis",
        "scrollTimelineAxis"
      ]
    },
    "scroll-timeline": {
      "name": "scroll-timeline",
      "value": "<'scroll-timeline-name'> || <'scroll-timeline-axis'>",
      "initial": "see individual properties",
      "appliesTo": "scroll containers",
      "inherited": "no",
      "percentages": "see individual properties",
      "computedValue": "see individual properties",
      "animationType": "not animatable",
      "canonicalOrder": "per grammar",
      "styleDeclaration": [
        "scroll-timeline",
        "scrollTimeline"
      ]
    },
    "view-timeline-name": {
      "name": "view-timeline-name",
      "value": "none | <custom-ident>#",
      "initial": "none",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "the keyword none or a list of <custom-ident>s",
      "canonicalOrder": "per grammar",
      "animationType": "not animatable",
      "styleDeclaration": [
        "view-timeline-name",
        "viewTimelineName"
      ]
    },
    "view-timeline-axis": {
      "name": "view-timeline-axis",
      "value": "[ block | inline | vertical | horizontal ]#",
      "initial": "block",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "n/a",
      "computedValue": "a list of the keywords specified",
      "canonicalOrder": "per grammar",
      "animationType": "not animatable",
      "styleDeclaration": [
        "view-timeline-axis",
        "viewTimelineAxis"
      ]
    },
    "view-timeline-inset": {
      "name": "view-timeline-inset",
      "value": "[ [ auto | <length-percentage> ]{1,2} ]#",
      "initial": "0",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "relative to the corresponding dimension of the relevant scrollport",
      "computedValue": "a list consisting of two-value pairs representing the start and end insets each as either the keyword auto or a computed <length-percentage> value",
      "canonicalOrder": "per grammar",
      "animationType": "by computed value type",
      "styleDeclaration": [
        "view-timeline-inset",
        "viewTimelineInset"
      ]
    },
    "view-timeline": {
      "name": "view-timeline",
      "value": "[ <'view-timeline-name'> || <'view-timeline-axis'> ]#",
      "initial": "see individual properties",
      "appliesTo": "all elements",
      "inherited": "see individual properties",
      "percentages": "see individual properties",
      "computedValue": "see individual properties",
      "animationType": "see individual properties",
      "canonicalOrder": "per grammar",
      "styleDeclaration": [
        "view-timeline",
        "viewTimeline"
      ]
    },
    "animation-delay": {
      "name": "animation-delay",
      "value": "[ <'animation-delay-start'> <'animation-delay-end'>? | <timeline-range-name> ]#",
      "initial": "see individual properties",
      "appliesTo": "see individual properties",
      "inherited": "see individual properties",
      "percentages": "see individual properties",
      "computedValue": "see individual properties",
      "animationType": "see individual properties",
      "canonicalOrder": "per grammar",
      "styleDeclaration": [
        "animation-delay",
        "animationDelay"
      ]
    },
    "animation-range": {
      "name": "animation-range",
      "value": "[ <'animation-delay-start'> <'animation-delay-end'>? | <timeline-range-name> ]#",
      "initial": "see individual properties",
      "appliesTo": "see individual properties",
      "inherited": "see individual properties",
      "percentages": "see individual properties",
      "computedValue": "see individual properties",
      "animationType": "see individual properties",
      "canonicalOrder": "per grammar",
      "styleDeclaration": [
        "animation-range",
        "animationRange"
      ]
    },
    "animation-delay-start": {
      "name": "animation-delay-start",
      "value": "[ <time> | <timeline-range-name> <percentage> ]",
      "initial": "0s",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "relative to the specified named timeline range",
      "computedValue": "list, each item either a duration or a timeline range and progress percentage",
      "canonicalOrder": "per grammar",
      "animatable": "no",
      "styleDeclaration": [
        "animation-delay-start",
        "animationDelayStart"
      ]
    },
    "animation-delay-end": {
      "name": "animation-delay-end",
      "value": "[ <time> | <timeline-range-name> <percentage> ]",
      "initial": "0s",
      "appliesTo": "all elements",
      "inherited": "no",
      "percentages": "relative to the specified named timeline range",
      "computedValue": "list, each item either a duration or a timeline range and progress percentage",
      "canonicalOrder": "per grammar",
      "animatable": "no",
      "styleDeclaration": [
        "animation-delay-end",
        "animationDelayEnd"
      ]
    }
  },
  "atrules": {},
  "valuespaces": {
    "<timeline-range-name>": {
      "prose": "A named timeline range is a named segment of an animation timeline. The start of the segment is represented as 0% progress through the range; the end of the segment is represented as 100% progress through the range. Multiple named timeline ranges can be attached to a given timeline, and multiple such ranges can overlap. For example, the contain range of a view progress timeline overlaps with its cover range. Named timeline ranges are represented by the <timeline-range-name> value type, which indicates a CSS identifier representing one of the predefined named timeline ranges."
    },
    "<scroll()>": {
      "value": "scroll( <axis>? <scroller>? )"
    },
    "<axis>": {
      "value": "block | inline | vertical | horizontal"
    },
    "<scroller>": {
      "value": "root | nearest"
    },
    "<keyframe-selector>": {
      "value": "from | to | <percentage> | <timeline-range-name> <percentage>"
    }
  }
}
